-- =============================================================================
-- NestHire upgrade 2/5 — task scheduling and execution model
--
--   * Lifecycle: NOT_STARTED → SCHEDULED → IN_PROGRESS → SUBMITTED →
--     UNDER_REVIEW → (REVISION_REQUIRED → IN_PROGRESS/SUBMITTED …) →
--     APPROVED → COMPLETED, plus BLOCKED and CANCELLED.
--     Existing rows are migrated: todo → not_started, review → submitted,
--     rejected → cancelled.
--   * Priorities P0 (critical) … P3 (low). Existing rows: critical → p0,
--     high → p1, medium → p2, low → p3.
--   * Scheduling: planned start, duration (+ unit, normalized to minutes),
--     due date/time (start + duration, calculated by the server unless a
--     supervisor overrides it), planning month/week (the plan, distinct from
--     actual dates) and the actual execution timestamps.
--   * Task ID (task_code), e.g. M01-GH-01-01: unique, immutable, generated by
--     the server unless a supervisor enters an existing ID.
--   * Visibility: PRIVATE until a reviewer marks the approved task as
--     completed; then a sanitized publication is created for the team.
--   * Versioned submissions, review records, dependencies, notifications.
--
-- The enum types are replaced (not extended with ADD VALUE) so the whole
-- upgrade can run inside one transaction (SQL Editor bundle).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Status and priority enums
-- -----------------------------------------------------------------------------
alter type public.task_status rename to task_status_legacy;
create type public.task_status as enum (
  'not_started',
  'scheduled',
  'in_progress',
  'blocked',
  'submitted',
  'under_review',
  'revision_required',
  'approved',
  'completed',
  'cancelled'
);

alter table public.tasks alter column status drop default;
alter table public.tasks
  alter column status type public.task_status
  using (
    case status::text
      when 'todo' then 'not_started'
      when 'review' then 'submitted'
      when 'rejected' then 'cancelled'
      else status::text
    end
  )::public.task_status;
alter table public.tasks alter column status set default 'not_started';
drop type public.task_status_legacy;

alter type public.task_priority rename to task_priority_legacy;
create type public.task_priority as enum ('p0', 'p1', 'p2', 'p3');

alter table public.tasks alter column priority drop default;
alter table public.tasks
  alter column priority type public.task_priority
  using (
    case priority::text
      when 'critical' then 'p0'
      when 'high' then 'p1'
      when 'medium' then 'p2'
      else 'p3'
    end
  )::public.task_priority;
alter table public.tasks alter column priority set default 'p2';
drop type public.task_priority_legacy;

create type public.duration_unit as enum ('hours', 'days', 'weeks');
create type public.task_visibility as enum ('private', 'team');
create type public.submission_status as enum ('submitted', 'under_review', 'revision_required', 'approved');
create type public.review_decision as enum ('approved', 'revision_required');

-- -----------------------------------------------------------------------------
-- New task columns
-- -----------------------------------------------------------------------------
alter table public.tasks
  add column task_code text,
  add column team_id uuid references public.teams (id) on delete set null,
  add column responsible_member_id uuid references public.team_members (id) on delete set null,
  add column original_instructions text not null default '',
  add column expected_output text not null default '',
  add column completion_criteria text not null default '',
  add column planning_month smallint not null default 1,
  add column planning_week smallint,
  add column planned_start_at timestamptz,
  add column planned_duration numeric(8, 2),
  add column duration_unit public.duration_unit,
  add column planned_duration_minutes integer,
  add column due_at timestamptz,
  add column due_at_overridden boolean not null default false,
  add column actual_start_at timestamptz,
  add column submitted_at timestamptz,
  add column approved_at timestamptz,
  add column progress smallint not null default 0,
  add column work_notes text not null default '',
  add column visibility public.task_visibility not null default 'private',
  add column published_at timestamptz;

comment on column public.tasks.task_code is 'Human task ID (e.g. M01-GH-01-01). Unique and immutable.';
comment on column public.tasks.responsible_member_id is
  'Roster entry responsible for the task. Lets a supervisor plan work for a member who has no account yet; assigned_to follows it.';
comment on column public.tasks.original_instructions is 'Instructions as given by the supervisor (kept as the reference).';
comment on column public.tasks.planning_month is 'Plan month (M01 = first month). Planning, not actual dates.';
comment on column public.tasks.planning_week is 'Plan week inside the month (Week 1–5). Planning, not actual dates.';
comment on column public.tasks.planned_duration_minutes is 'Duration normalized to minutes (server-calculated).';
comment on column public.tasks.due_at is 'Deadline. planned_start_at + duration unless due_at_overridden.';
comment on column public.tasks.actual_start_at is 'Set by the server when the task first moves to IN_PROGRESS.';
comment on column public.tasks.visibility is 'PRIVATE until marked as completed; never written by clients.';

-- Existing due dates become end-of-day deadlines in the organization's time zone.
update public.tasks
   set due_at = ((due_date + time '23:59') at time zone 'Asia/Gaza'),
       due_at_overridden = true
 where due_date is not null;

alter table public.tasks drop column due_date;

alter table public.tasks
  add constraint tasks_task_code_format check (task_code ~ '^[A-Z0-9]{1,12}(-[A-Z0-9]{1,12}){0,5}$'),
  add constraint tasks_original_instructions_length check (char_length(original_instructions) <= 10000),
  add constraint tasks_expected_output_length check (char_length(expected_output) <= 5000),
  add constraint tasks_completion_criteria_length check (char_length(completion_criteria) <= 5000),
  add constraint tasks_work_notes_length check (char_length(work_notes) <= 10000),
  add constraint tasks_planning_month_range check (planning_month between 1 and 99),
  add constraint tasks_planning_week_range check (planning_week is null or planning_week between 1 and 5),
  add constraint tasks_planned_duration_range check (planned_duration is null or (planned_duration > 0 and planned_duration <= 1000)),
  add constraint tasks_duration_unit_pair check ((planned_duration is null) = (duration_unit is null)),
  add constraint tasks_due_after_start check (due_at is null or planned_start_at is null or due_at >= planned_start_at),
  add constraint tasks_progress_range check (progress between 0 and 100);

create index tasks_team_idx on public.tasks (team_id) where team_id is not null;
create index tasks_responsible_member_idx on public.tasks (responsible_member_id) where responsible_member_id is not null;
create index tasks_project_due_at_idx on public.tasks (project_id, due_at) where due_at is not null;
create index tasks_assigned_due_at_idx on public.tasks (assigned_to, due_at) where assigned_to is not null;
create index tasks_planned_start_idx on public.tasks (planned_start_at) where planned_start_at is not null;
create index tasks_planning_idx on public.tasks (project_id, planning_month, planning_week);

-- -----------------------------------------------------------------------------
-- Task ID generation
-- -----------------------------------------------------------------------------

-- M<month>-<member code>-<week>-<sequence>, e.g. M01-GH-01-01. The member code
-- comes from the responsible roster entry (or the assignee's entry) in the
-- task's team ("NA" when there is none); week 00 = no week planned.
create or replace function private.next_task_code_for(p_member_code text, p_month integer, p_week integer)
returns text
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_prefix text;
  v_next integer;
begin
  v_prefix := format(
    'M%s-%s-%s-',
    lpad(coalesce(p_month, 1)::text, 2, '0'),
    coalesce(nullif(p_member_code, ''), 'NA'),
    lpad(coalesce(p_week, 0)::text, 2, '0')
  );
  -- Serialize generators of the same prefix (concurrent inserts).
  perform pg_advisory_xact_lock(hashtext('task_code:' || v_prefix));

  select coalesce(max(substring(t.task_code from length(v_prefix) + 1)::integer), 0) + 1
    into v_next
  from public.tasks t
  where t.task_code like v_prefix || '%'
    and substring(t.task_code from length(v_prefix) + 1) ~ '^[0-9]{1,6}$';

  return v_prefix || lpad(v_next::text, 2, '0');
end;
$$;

create or replace function private.next_task_code(
  p_team_id uuid,
  p_assignee uuid,
  p_month integer,
  p_week integer
)
returns text
language sql
volatile
security definer
set search_path = ''
as $$
  select private.next_task_code_for(private.team_member_code(p_team_id, p_assignee), p_month, p_week);
$$;

update public.tasks t
   set task_code = private.next_task_code(t.team_id, t.assigned_to, t.planning_month, t.planning_week)
 where t.task_code is null;

alter table public.tasks alter column task_code set not null;
-- An empty ID on insert means "generate it" (private.tasks_before_insert).
alter table public.tasks alter column task_code set default '';
create unique index tasks_task_code_key on public.tasks (task_code);

-- -----------------------------------------------------------------------------
-- Dependencies (predecessors)
-- -----------------------------------------------------------------------------
create table public.task_dependencies (
  task_id uuid not null,
  depends_on_task_id uuid not null,
  project_id uuid not null,
  created_by uuid default auth.uid() references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (task_id, depends_on_task_id),
  constraint task_dependencies_not_self check (task_id <> depends_on_task_id),
  constraint task_dependencies_task_fkey foreign key (task_id, project_id)
    references public.tasks (id, project_id) on delete cascade,
  constraint task_dependencies_predecessor_fkey foreign key (depends_on_task_id, project_id)
    references public.tasks (id, project_id) on delete cascade
);
comment on table public.task_dependencies is 'A task cannot start before all its predecessors are approved or completed.';
create index task_dependencies_predecessor_idx on public.task_dependencies (depends_on_task_id);

-- -----------------------------------------------------------------------------
-- Submissions (versioned, never overwritten)
-- -----------------------------------------------------------------------------
create or replace function private.valid_links(p_links text[])
returns boolean
language sql
immutable
set search_path = ''
as $$
  select coalesce(cardinality(p_links), 0) <= 10
     and not exists (
       select 1 from unnest(coalesce(p_links, '{}'::text[])) as l
       where l !~ '^https?://[^\s]+$' or char_length(l) > 2048
     );
$$;

create table public.task_submissions (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null,
  project_id uuid not null,
  version integer not null,
  summary text not null,
  deliverable_links text[] not null default '{}',
  notes text not null default '',
  status public.submission_status not null default 'submitted',
  is_final boolean not null default false,
  submitted_by uuid references public.profiles (id) on delete set null,
  submitted_at timestamptz not null default now(),
  constraint task_submissions_version_key unique (task_id, version),
  constraint task_submissions_version_positive check (version > 0),
  constraint task_submissions_summary_length check (char_length(btrim(summary)) between 1 and 10000),
  constraint task_submissions_notes_length check (char_length(notes) <= 5000),
  constraint task_submissions_links_valid check (private.valid_links(deliverable_links)),
  constraint task_submissions_task_fkey foreign key (task_id, project_id)
    references public.tasks (id, project_id) on delete cascade
);
comment on table public.task_submissions is
  'Every submission and resubmission of a task as its own version. Private: visible only to whoever can see the task.';
create unique index task_submissions_single_final_idx on public.task_submissions (task_id) where is_final;

-- -----------------------------------------------------------------------------
-- Reviews
-- -----------------------------------------------------------------------------
create table public.task_reviews (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null,
  project_id uuid not null,
  submission_id uuid not null references public.task_submissions (id) on delete cascade,
  decision public.review_decision not null,
  comment text not null default '',
  required_changes text not null default '',
  additional_instructions text not null default '',
  previous_due_at timestamptz,
  new_due_at timestamptz,
  reviewer_id uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  constraint task_reviews_comment_length check (char_length(comment) <= 5000),
  constraint task_reviews_required_changes_length check (char_length(required_changes) <= 5000),
  constraint task_reviews_instructions_length check (char_length(additional_instructions) <= 5000),
  constraint task_reviews_task_fkey foreign key (task_id, project_id)
    references public.tasks (id, project_id) on delete cascade
);
comment on table public.task_reviews is 'Review decisions on submissions. Private (supervisors and the responsible member).';
create index task_reviews_task_idx on public.task_reviews (task_id, created_at);

-- -----------------------------------------------------------------------------
-- Team publications (the only part of a task the team can see)
-- -----------------------------------------------------------------------------
create table public.task_publications (
  task_id uuid primary key,
  project_id uuid not null references public.projects (id) on delete cascade,
  team_id uuid references public.teams (id) on delete set null,
  task_code text not null,
  title text not null,
  responsible_id uuid references public.profiles (id) on delete set null,
  responsible_name text,
  responsible_title text,
  final_result text not null,
  deliverable_links text[] not null default '{}',
  team_comment text not null default '',
  final_submission_version integer not null,
  completed_at timestamptz not null,
  published_by uuid references public.profiles (id) on delete set null,
  published_at timestamptz not null default now(),
  constraint task_publications_team_comment_length check (char_length(team_comment) <= 5000),
  constraint task_publications_task_fkey foreign key (task_id, project_id)
    references public.tasks (id, project_id) on delete cascade
);
comment on table public.task_publications is
  'Sanitized final result of a completed task, published to its team. Contains no drafts, earlier versions, review notes or private notes.';
create index task_publications_team_idx on public.task_publications (team_id, completed_at desc);
create index task_publications_project_idx on public.task_publications (project_id, completed_at desc);

-- -----------------------------------------------------------------------------
-- Notifications
-- -----------------------------------------------------------------------------
create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  project_id uuid references public.projects (id) on delete cascade,
  task_id uuid references public.tasks (id) on delete cascade,
  type text not null,
  data jsonb not null default '{}'::jsonb,
  actor_id uuid,
  actor_name text,
  read_at timestamptz,
  created_at timestamptz not null default clock_timestamp(),
  constraint notifications_type_format check (type ~ '^[a-z_]+$')
);
comment on table public.notifications is 'In-app notifications. Written only by the database; users read and dismiss their own.';
create index notifications_user_created_idx on public.notifications (user_id, created_at desc);
create index notifications_user_unread_idx on public.notifications (user_id) where read_at is null;

create or replace function private.notify(
  p_user_id uuid,
  p_type text,
  p_project_id uuid,
  p_task_id uuid,
  p_data jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_user_id is null or p_user_id is not distinct from auth.uid() then
    return;
  end if;
  insert into public.notifications (user_id, project_id, task_id, type, data, actor_id, actor_name)
  values (p_user_id, p_project_id, p_task_id, p_type, coalesce(p_data, '{}'::jsonb), auth.uid(), private.profile_name(auth.uid()));
end;
$$;

-- Submissions migrated from the previous "review" status get a version 1 so
-- that reviewers can act on them.
insert into public.task_submissions (task_id, project_id, version, summary, submitted_by, submitted_at)
select t.id, t.project_id, 1, 'Submitted before the scheduling upgrade.', t.assigned_to, t.updated_at
from public.tasks t
where t.status = 'submitted';

update public.tasks t set submitted_at = t.updated_at where t.status = 'submitted' and t.submitted_at is null;

-- Tasks of projects that already belong to a team.
update public.tasks t set team_id = p.team_id from public.projects p where p.id = t.project_id and p.team_id is not null;
