/**
 * Bundles every migration into one SQL script for the Supabase SQL Editor —
 * the no-CLI way to set up a hosted project:
 *
 *   npm run db:bundle                 # writes supabase-setup.sql
 *   npm run db:bundle -- other.sql    # custom output path
 *
 * The script runs in a single transaction (all or nothing), refuses to run on
 * a database where the platform is already installed, and records the
 * migrations in supabase_migrations.schema_migrations exactly like
 * `supabase db push` does, so the CLI can apply future migrations later.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const MIGRATIONS_DIR = path.resolve(import.meta.dirname, "../supabase/migrations");
const MIGRATION_FILE = /^(\d+)_(.+)\.sql$/;

async function main() {
  const output = path.resolve(process.cwd(), process.argv[2] ?? "supabase-setup.sql");
  const migrations = (await readdir(MIGRATIONS_DIR))
    .map((file) => ({ file, match: MIGRATION_FILE.exec(file) }))
    .filter((entry): entry is { file: string; match: RegExpExecArray } => entry.match !== null)
    .sort((a, b) => a.file.localeCompare(b.file));
  if (migrations.length === 0) throw new Error(`No migrations found in ${MIGRATIONS_DIR}.`);

  const parts = [
    [
      "-- =============================================================================",
      "-- Research Team Platform — complete database setup for a NEW Supabase project.",
      "-- Paste into Supabase Dashboard → SQL Editor → New query, then click Run.",
      `-- Generated by \`npm run db:bundle\` from ${migrations.length} migrations; run it only once.`,
      "-- =============================================================================",
    ].join("\n"),
    "begin;",
    `do $$
begin
  if to_regclass('public.projects') is not null then
    raise exception 'The Research Team Platform schema already exists in this database. Nothing was changed.';
  end if;
end;
$$;`,
  ];

  for (const { file } of migrations) {
    const sql = await readFile(path.join(MIGRATIONS_DIR, file), "utf8");
    parts.push(`-- >>> ${file}`, sql.trim());
  }

  const versions = migrations.map(({ match }) => `  ('${match[1]}', '${match[2]}')`).join(",\n");
  parts.push(
    "-- >>> Record the migrations as applied (same table the Supabase CLI uses).",
    `create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (version text not null primary key);
alter table supabase_migrations.schema_migrations add column if not exists statements text[];
alter table supabase_migrations.schema_migrations add column if not exists name text;
insert into supabase_migrations.schema_migrations (version, name) values
${versions}
on conflict (version) do nothing;`,
    "commit;",
  );

  await writeFile(output, `${parts.join("\n\n")}\n`, "utf8");
  console.log(`Wrote ${path.relative(process.cwd(), output) || output} (${migrations.length} migrations).`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
